### ISSUE TITLE
Release tags 

### ISSUE THREAD

**Issue by druppy** [javierEd/leptos-bulma#1]
Thanks for your work on this handy lib.

I just tried it (I am a Rust noop) and was confused about the docs on you readme (`build.rs` setup), and how it did not work in my code (used ...alpha.7).

It would be lovely and less confusion if the releases in `create.io` was also release tags in github.

Also, just a simple "hello world" example.

**Comment by javierEd** [comment]
> Thanks for your work on this handy lib.
> 
> I just tried it (I am a Rust noop) and was confused about the docs on you readme (`build.rs` setup), and how it did not work in my code (used ...alpha.7).
> 
> It would be lovely and less confusion if the releases in `create.io` was also release tags in github.
> 
> Also, just a simple "hello world" example.

Hi. Thank you for trying the library and also for your suggestions.

And sorry for the late reply.

Right now, I think the library is in a pretty early stage. So I'm constantly adding and changing stuff.
But I'm planning to start with the release tags once It reaches some stability and covers the majority of Bulma features.

And if you are looking for a good example, the official website could be one: https://github.com/javierEd/leptos-bulma/tree/main/website
It's using `spin` for SSR, but it should work the same with `actix` or `axum`.

I'm closing this issue, but I'll create a roadmap with all the pending tasks for the first stable release, and including your suggestions.
